#galSim: FinalPro_GalSim.cpp
#	g++	-o galSim FinalPro_GalSim.cpp -framework Carbon -framework OpenGL -framework GLUT -w

galSim: FinalPro_GalSim.cpp
	g++	-o galSim FinalPro_GalSim.cpp -lGL -lGLU -lglut
